name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgbm-dev x11-xkb-utils  

      - name: Run tests
        run: |
          export DISPLAY=:0
          Xvfb :0 -screen 0 1280x720x24 >/dev/null 2>&1 &  
          mvn clean test -B

        stages:
            - test

        e2e_tests:
            stage: test
            image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
            script:
              - mvn test
        artifacts:
            paths:
                - target/screenshots/  # Директория со скриншотами
                - target/videos/       # Директория с видео
            when: always             # Сохранять даже при падении тестов
            expire_in: 7 days        # Автоудаление через неделю
